# Generated by Django 3.2.3 on 2021-06-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='user',
            field=models.CharField(default='guest', max_length=20),
        ),
    ]
