# Generated by Django 3.2.3 on 2021-06-03 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_stock_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
